apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for" '
                       '"$http_x_cbt_bucket" "$http_host" "$http_accept"';

    access_log  /dev/stdout  main;
    error_log   /dev/stderr notice;

    lua_shared_dict bucket_cache 10m;

    init_by_lua_block {
      package.path = "/etc/nginx/lua/?.lua;" .. package.path
      require("script").load_buckets()
    }

    upstream aws_upstream {
      server minio-aws.default.svc.cluster.local:8080;
    }

    upstream witt_upstream {
      server minio-witt.default.svc.cluster.local:8080;
    }

    server {
      listen 80;

      set $upstream "";
      access_by_lua_block {
        require("script").select_upstream()
      }

      location / {
        proxy_pass http://$upstream;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lua-script
data:
  script.lua: |
    local ngx_shared_cache = ngx.shared.bucket_cache

    local function load_buckets()
      local file = io.open("/etc/nginx/conf.d/buckets.txt", "r")
        if file then
          ngx.log(ngx.NOTICE, "loading buckets into memory")
          ngx_shared_cache:flush_all()
          for line in file:lines() do
            ngx_shared_cache:set(line, true)
          end
          file:close()
        else
          ngx.log(ngx.ERR, "Error: cannot open /etc/nginx/conf.d/buckets.txt")
        end
    end

    local function select_upstream()
      local bucket = ngx.var.http_x_cbt_bucket
      if bucket and ngx_shared_cache:get(bucket) then
        ngx.log(ngx.NOTICE, "forwarding request to witt")
        gx.var.upstream = "witt_upstream"
      else
        ngx.log(ngx.NOTICE, "forwarding request to aws")
        ngx.var.upstream = "aws_upstream"
      end
    end

    return {
      load_buckets = load_buckets,
      select_upstream = select_upstream
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buckets
  namespace: default
data:
  buckets: |
    bucket1
    bucket2
    bucket3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: buckets
        - name: lua-script-volume
          configMap:
            name: lua-script
        - name: nginx-conf-volume
          configMap:
            name: nginx-conf
      containers:
        - name: nginx
          image: openresty/openresty:latest
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/buckets.txt
              subPath: buckets
            - name: lua-script-volume
              mountPath: /etc/nginx/lua/script.lua
              subPath: script.lua
            - name: nginx-conf-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
